// PRODUCT
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAILURE = 'PRODUCT_LIST_FAILURE'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAILURE = 'PRODUCT_DELETE_FAILURE'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAILURE = 'PRODUCT_CREATE_FAILURE'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_EDIT_REQUEST = 'PRODUCT_EDIT_REQUEST'
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS'
export const PRODUCT_EDIT_FAILURE = 'PRODUCT_EDIT_FAILURE'
export const PRODUCT_EDIT_RESET = 'PRODUCT_EDIT_RESET'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAILURE = 'PRODUCT_UPDATE_FAILURE'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

// CATEGORY
export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST'
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'
export const CATEGORY_LIST_FAILURE = 'CATEGORY_LIST_FAILURE'

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST'
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS'
export const CATEGORY_DELETE_FAILURE = 'CATEGORY_DELETE_FAILURE'
export const CATEGORY_DELETE_RESET = 'CATEGORY_DELETE_RESET'

export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST'
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS'
export const CATEGORY_CREATE_FAILURE = 'CATEGORY_CREATE_FAILURE'
export const CATEGORY_CREATE_RESET = 'CATEGORY_CREATE_RESET'

export const CATEGORY_EDIT_REQUEST = 'CATEGORY_EDIT_REQUEST'
export const CATEGORY_EDIT_SUCCESS = 'CATEGORY_EDIT_SUCCESS'
export const CATEGORY_EDIT_FAILURE = 'CATEGORY_EDIT_FAILURE'
export const CATEGORY_EDIT_RESET = 'CATEGORY_EDIT_RESET'

export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST'
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS'
export const CATEGORY_UPDATE_FAILURE = 'CATEGORY_UPDATE_FAILURE'
export const CATEGORY_UPDATE_RESET = 'CATEGORY_UPDATE_RESET'

// COUPON
export const COUPON_LIST_REQUEST = 'COUPON_LIST_REQUEST'
export const COUPON_LIST_SUCCESS = 'COUPON_LIST_SUCCESS'
export const COUPON_LIST_FAILURE = 'COUPON_LIST_FAILURE'

export const COUPON_DELETE_REQUEST = 'COUPON_DELETE_REQUEST'
export const COUPON_DELETE_SUCCESS = 'COUPON_DELETE_SUCCESS'
export const COUPON_DELETE_FAILURE = 'COUPON_DELETE_FAILURE'
export const COUPON_DELETE_RESET = 'COUPON_DELETE_RESET'

export const COUPON_CREATE_REQUEST = 'COUPON_CREATE_REQUEST'
export const COUPON_CREATE_SUCCESS = 'COUPON_CREATE_SUCCESS'
export const COUPON_CREATE_FAILURE = 'COUPON_CREATE_FAILURE'
export const COUPON_CREATE_RESET = 'COUPON_CREATE_RESET'

export const COUPON_EDIT_REQUEST = 'COUPON_EDIT_REQUEST'
export const COUPON_EDIT_SUCCESS = 'COUPON_EDIT_SUCCESS'
export const COUPON_EDIT_FAILURE = 'COUPON_EDIT_FAILURE'
export const COUPON_EDIT_RESET = 'COUPON_EDIT_RESET'

export const COUPON_UPDATE_REQUEST = 'COUPON_UPDATE_REQUEST'
export const COUPON_UPDATE_SUCCESS = 'COUPON_UPDATE_SUCCESS'
export const COUPON_UPDATE_FAILURE = 'COUPON_UPDATE_FAILURE'
export const COUPON_UPDATE_RESET = 'COUPON_UPDATE_RESET'

// COLOR
export const COLOR_LIST_REQUEST = 'COLOR_LIST_REQUEST'
export const COLOR_LIST_SUCCESS = 'COLOR_LIST_SUCCESS'
export const COLOR_LIST_FAILURE = 'COLOR_LIST_FAILURE'

export const COLOR_CREATE_REQUEST = 'COLOR_CREATE_REQUEST'
export const COLOR_CREATE_SUCCESS = 'COLOR_CREATE_SUCCESS'
export const COLOR_CREATE_FAILURE = 'COLOR_CREATE_FAILURE'
export const COLOR_CREATE_RESET = 'COLOR_CREATE_RESET'

export const COLOR_DELETE_REQUEST = 'COLOR_DELETE_REQUEST'
export const COLOR_DELETE_SUCCESS = 'COLOR_DELETE_SUCCESS'
export const COLOR_DELETE_FAILURE = 'COLOR_DELETE_FAILURE'
export const COLOR_DELETE_RESET = 'COLOR_DELETE_RESET'

export const COLOR_EDIT_REQUEST = 'COLOR_EDIT_REQUEST'
export const COLOR_EDIT_SUCCESS = 'COLOR_EDIT_SUCCESS'
export const COLOR_EDIT_FAILURE = 'COLOR_EDIT_FAILURE'
export const COLOR_EDIT_RESET = 'COLOR_EDIT_RESET'

// CART
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const REMOVE_ALL_CART_ITEMS = 'REMOVE_ALL_CART_ITEMS'

// USER
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'
export const USER_LOGOUT = 'USER_LOGOUT'

// REGISTER
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE'

// GET USER DETAILS
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAILURE = 'USER_DETAILS_FAILURE'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

// UPDATE USER PROFILE
export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAILURE = 'USER_UPDATE_PROFILE_FAILURE'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

// GET LIST OF USERS
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAILURE = 'USER_LIST_FAILURE'
export const USER_LIST_RESET = 'USER_LIST_RESET'

// SAVE SHIPPING ADDRESS
export const SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS'
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD'

// ORDER
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAILURE = 'ORDER_CREATE_FAILURE'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAILURE = 'ORDER_DELIVER_FAILURE'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'

// ORDER DETAILS
export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAILURE = 'ORDER_DETAILS_FAILURE'

// ORDER PAY
export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAILURE = 'ORDER_PAY_FAILURE'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

// ORDER LIST MY
export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST'
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS'
export const ORDER_LIST_MY_FAILURE = 'ORDER_LIST_MY_FAILURE'
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET'

// REVIEW
export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST'
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS'
export const REVIEW_CREATE_FAILURE = 'REVIEW_CREATE_FAILURE'
export const REVIEW_CREATE_RESET = 'REVIEW_CREATE_RESET'
